version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-fitness-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - ai-fitness-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ai-fitness-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      - redis
    networks:
      - ai-fitness-network

volumes:
  redis_data:
    driver: local

networks:
  ai-fitness-network:
    driver: bridge